### ISSUE TITLE
Issue with Sitecore JSS: Cannot read properties of undefined (reading 'route')

### ISSUE THREAD

**Issue by HermonSolomon** [Sitecore/jss#1567]
### Describe the Bug

I am encountering an issue with Sitecore JSS while working on my new app which is using NextJS 13 (Disconnected mode). After creating the app using the JSS CLI and starting it, I am facing the following error:

`Error [TypeError]: Cannot read properties of undefined (reading 'route')
    at NormalModePlugin.exec (webpack-internal:///./src/lib/page-props-factory/plugins/normal-mode.ts:39:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (webpack-internal:///./src/lib/page-props-factory/index.ts:26:24)
    at async eval (webpack-internal:///./src/lib/page-props-factory/index.ts:25:21)
    at async eval (webpack-internal:///./src/lib/page-props-factory/index.ts:25:21)
    at async SitecorePagePropsFactory.create (webpack-internal:///./src/lib/page-props-factory/index.ts:24:27)
    at async getServerSideProps (webpack-internal:///./src/pages/[[...path]].tsx:79:17) {
  digest: undefined
}
  37 |     );
  38 | 
> 39 |     if (!props.layoutData.sitecore.route) {
     |                                   ^
  40 |       // A missing route value signifies an invalid path, so set notFound.
  41 |       // Our page routes will return this in getStatic/ServerSideProps,
  42 |       // which will trigger our custom 404 page with proper 404 status code. `

From the error message, it seems that the props.layoutData.sitecore.route is undefined, leading to a TypeError. I believe this issue might be related to a bug on the Sitecore JSS side or some misconfiguration in my app.

Things I have already checked:

    Verified the route configuration in Sitecore.
    Reviewed my code for any issues with data fetching or usage.

### To Reproduce

    1) Create a new app using the JSS CLI.
    2) Start the application.
    3) Observe the error in the console.

### Expected Behavior

The application should start without any errors, and the props.layoutData.sitecore.route object should be populated with the expected data.

### Provide environment information

* Sitecore Version: 10 
* JSS Version: @sitecore-jss/sitecore-jss-nextjs": "^21.1.1"
* Browser Name and version: Firefox, Chorme
* Operating System and version (desktop or mobile): Mac OS
* Link to your project (if available):

**Comment by ravivadher030** [comment]
(Connected mode) this error occur whenever we use general link field and we are providing an internal link to it, rather than you need to use an general link with search in your Sitecore instance.

**Comment by illiakovalenko** [comment]
@HermonSolomon I couldn't reproduce this issue using the latest version, if you can provide more details (in case you have any customizations), feel free to reopen the issue
