### ISSUE TITLE
Issue with adding a new component  in Experience Editor in Sitecore JSS

### ISSUE THREAD

**Issue by spal870** [Sitecore/jss#389]
## Description
Hi Team,
We are facing issue while trying to add new component through sitecore experience editor while using Sitecore JSS sample app(https://jss.sitecore.com/docs/getting-started/quick-start).
When we are trying to add new component Content Block in Experience Editor in main placeholder and its giving me error saying "An error occured".
Please find below error logged for the same---

33380 19:16:29 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.InvalidOperationException
Message: placeholderKey
Source: Sitecore.ExperienceEditor
at Sitecore.Pipelines.ExecutePageEditorAction.InsertRendering.Process(PipelineArgs args)
at (Object , Object )
at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
at Sitecore.Pipelines.ExecutePageEditorAction.ExecutePageEditorActionPipeline.Run(ExecutePageEditorActionArgs args)
at Sitecore.Shell.Applications.WebEdit.Palette.OnPreInit(EventArgs e)
at System.Web.UI.Page.PerformPreInit()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

We have checked with sitecore and we come to know that the which  html getting render is as below  has some issue.
 <code type="text/sitecore" chrometype="placeholder" kind="open" id="jss_main" class="scpm" data-selectable="true" phkey="jss-main" key="jss-main">........</code>
Here "**key**" attribute is missing

Please note that in this  sitecore instance React CLI(sitecore-jss/sitecore-jss-react) version is "13.0.5" and the error it is throwing is "Placholder key is missing".
But when we tried older  React CLI version 13.0.0. it was working as expected.
 
I have observed another issue in the same instance having React CLI(sitecore-jss/sitecore-jss-react) version is "13.0.5".
Javascript click event is not working in the preview mode.

## Expected behavior
Editor should be able to add new component in page through experience editor . Also in preview mode Javascript event should work.

## Steps To Reproduce

1. Go to  "home" page react react sample app in sitecore content editor
2. Open the page in experience editor
3.Try to add component "Content Block"in main placeholder

## Possible Fix
NA

## Your Environment

* Sitecore Version: 9.3
* JSS Version: 13.0.0
* Browser Name and version: Chrome ,Version 83.0.4103.106 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10,Desktop
* Link to your project (if available):

## Screenshots
![Error while adding ContentBlock in Main](https://user-images.githubusercontent.com/20183669/85506202-83c86580-b60d-11ea-83d2-1f6e7801cab2.JPG)

**Comment by sc-illiakovalenko** [comment]
@spal870 Fix was provided in JSS 13.1.0.
You can look at this fix: https://github.com/Sitecore/jss/pull/343

**Comment by sc-illiakovalenko** [comment]
@spal870 About onClick event, please, check it on the latest version (13.2.0). If it will happen, please provide
exact steps to reproduce, probably in separate ticket.
Feel free to reopen issue if you will have any problems, questions
