### ISSUE TITLE
ImportPipelineArgs.ImportData is not cleared during import retry

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#405]
## Description

`jss deploy items` command errors out on the server-side if there are some unresolvable id references (`ImportPipelineArgs.UnresolvableIdReferenceItemRetryList.Count  > 0`) due specifically after the re-try import is triggered (message from CLI):
>Retrying import job due to 24 initially unresolvable ID references.

At the end of this process the following exception will occur:
```
Exception thrown while importing JSS app
Exception: System.InvalidOperationException
Message: The ID {86D96BD8-34F4-5B25-99BC-C67B932254D0} has been used more than once during import. This likely means two imported items have the same id value, or two items of the same type (e.g. templates) share the same name. Details: template ABC Rendering Parameters, template ABC Rendering Parameters
Source: Sitecore.JavaScriptServices.AppServices
   at Sitecore.JavaScriptServices.AppServices.Data.IdManager.AssertIdIsUnused(ID id, String idUsageDescription)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ProcessTemplates.CreateTemplate(TemplateDef templateDef, Item parent, Item multilistRoot, AppConfiguration app, IdManager idManager)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ProcessTemplates.<CreateTemplates>d__11.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at jssextensions.Pipelines.Import.ProcessTemplates.Process(ImportPipelineArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ImportPipeline.Import(ImportPipelineArgs args)
   at Sitecore.JavaScriptServices.AppServices.ImportService.ImportJob.ProcessRetries(ImportPipelineArgs args)
   at Sitecore.JavaScriptServices.AppServices.ImportService.ImportJob.StartImportInternal()

```

This is due to the `ImportPipelineArgs.ImportData.*` properties not being cleared before re-try is initiated. Other pipeline arg state fields are cleared but not ImportData, which during the re-try gets duplicate templates in thanks to `Sitecore.JavaScriptServices.AppServices.Pipelines.Import.Deserialize` pipeline processor.

## Expected behavior

Re-try operation succeeds without errors.

## Steps To Reproduce

Provided above.

## Possible Fix

Clear the values for all the array properties inside `args.ImportData` object before issuing re-try of the import pipeline in side`ImportJob.ProcessRetries()` method.

## Your Environment

* Sitecore Version: 9.3
* JSS Version: 13.0.2 (latest)
* Browser Name and version: Netscape :)
* Operating System and version (desktop or mobile): Windows ME :)

**Comment by sc-illiakovalenko** [comment]
@alexshyba I shown it to team. Added in backlog to review

**Comment by anton-ovch-sitecore** [comment]
@alexshyba Could you please provide us items, templates structure, can't reproduce the issue?

**Comment by nickwesselman** [comment]
@alexshyba Any chance of getting an import from you which reproduces the issue?

**Comment by nickwesselman** [comment]
Unable to repro and no reply
