### ISSUE TITLE
JSS Deploy: Unexpected value type for media field (System.String)

### ISSUE THREAD

**Issue by jasonjohnlee** [Sitecore/jss#441]
## Description
Hi,  
I'm attempting to perform a `jss deploy app -c -d` on our JSS React application, but I get a very ambiguous error

IMPORT ERROR(S) OCCURRED!  
Exception thrown while importing JSS app  
Exception: System.InvalidOperationException  
Message: Unexpected value type for media field (System.String).

What does this error mean?  What happens on the line of code I mentioned in the stack trace since it's coming from Sitecore's .NET server code that I don't think is publicly shared?  We don't have the word "media" anywhere in our code or any of our Sitecore items.  The application runs correctly in disconnected mode.

We were successfully deploying a week ago, not sure what we would have done to break this since the error message and stack trace is very ambiguous.

The stack trace makes it look like it's related to Images, but I double checked where we use them in our renderings and items, and things look fine.  I also tried removing every image reference (I think) from our application and executed a deploy, but got the same results.

## Expected behavior
A successful deploy.  

## Steps To Reproduce
1. Open Powershell.
2. cd to the root of the application (i.e. where package.json is located)
2. Execute `jss deploy app -c -d`

## Your Environment

* Sitecore Version: 9.3
* JSS Version: "@sitecore-jss/sitecore-jss-cli": "^12.0.0",
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): Windows
* Link to your project (if available):

## Error logs
Here is the full log from my log*.txt.

ManagedPoolThread #10 18:22:13 INFO  Job started: JSSImport-internal-portal-6:22:13 PM
ManagedPoolThread #10 18:22:13 INFO  [JSS] - Importing internal-portal as sitecore\JssImport
ManagedPoolThread #10 18:22:13 INFO  Cache created: 'jssImport[html]' (max size: 0 bytes, running total: 4554MB)
ManagedPoolThread #10 18:22:13 INFO  Cache created: 'jssImport[registry]' (max size: 25MB, running total: 4579MB)
ManagedPoolThread #10 18:22:13 INFO  Cache created: 'jssImport[viewstate]' (max size: 25MB, running total: 4604MB)
ManagedPoolThread #10 18:22:13 INFO  Cache created: 'jssImport[xsl]' (max size: 50MB, running total: 4654MB)
ManagedPoolThread #10 18:22:13 INFO  Cache created: 'jssImport[filtered items]' (max size: 10MB, running total: 4664MB)
ManagedPoolThread #10 18:22:13 INFO  [JSS] - Import database is master
ManagedPoolThread #10 18:22:13 INFO  [JSS] - Import data contains:
	Templates - 23
	Renderings - 16
	Placeholders - 6
	Route Items - 5
	Other Items - 26
	Dictionary Items - 106

ManagedPoolThread #10 18:22:13 INFO  [JSS] - Import language is en
ManagedPoolThread #10 18:22:16 ERROR [JSS] - Exception thrown while importing JSS app
Exception: System.InvalidOperationException
Message: Unexpected value type for media field (System.String).
Source: Sitecore.JavaScriptServices.AppServices
   at Sitecore.JavaScriptServices.AppServices.Pipelines.ImportField.ImageFieldValue.SetFieldValue(ImportFieldArgs args)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.ImportField.BaseImportFieldValue.Process(ImportFieldArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.UpdateItem.SetFieldValues.Process(CreateItemArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.CreateItem.CreateItemPipeline.CreateOrUpdate(CreateItemArgs args)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.CreateRenderingInstance.CreateDatasourceItem.CreateItem(CreateRenderingInstanceArgs args)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.CreateRenderingInstance.CreateDatasourceItem.Process(CreateRenderingInstanceArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.CreateRenderingInstance.CreateRenderingInstancePipeline.CreateRenderingInstance(CreateRenderingInstanceArgs args)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.ImportLayout.AddRenderings.Process(ImportLayoutArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.CreateItem.CreateItemPipeline.CreateOrUpdate(CreateItemArgs args)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.CreateItem.CreateChildItems.Process(CreateItemArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.CreateItem.CreateItemPipeline.CreateOrUpdate(CreateItemArgs args)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ProcessItems.CreateItems(ImportPipelineArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ImportPipeline.Import(ImportPipelineArgs args)
   at Sitecore.JavaScriptServices.AppServices.ImportService.ImportJob.StartImportInternal()

ManagedPoolThread #10 18:22:16 INFO  Job ended: JSSImport-internal-portal-6:22:13 PM (units processed: )
ManagedPoolThread #8 18:22:16 INFO  Job started: Index_Update_IndexName=sitecore_master_index

**Comment by sc-illiakovalenko** [comment]
@jasonjohnlee This error means that you have incorrect value for media field. I reproduced it:
If I setup `sample1` field value as string - so I'm getting same error: `Message: Unexpected value type for media field (System.String).`
`routes/styleguide/en.yml`.
```yml
- componentName: Styleguide-FieldUsage-Image
     fields:
            heading: Image
            sample1: /data/media/img/sc_logo.png
            sample2:
              src: /data/media/img/jss_logo.png
              alt: Sitecore JSS Logo
```

It should be defined using `src` and `alt` properties:
```yml
- componentName: Styleguide-FieldUsage-Image
      fields:
            heading: Image
            sample1:
              src: /data/media/img/sc_logo.png
              alt: Sitecore Logo
            sample2:
              src: /data/media/img/jss_logo.png
              alt: Sitecore JSS Logo
```

So, carefully, check values of your items. Feel free to reopen issue if you will not find a cause of issue.
