### ISSUE TITLE
[Build error] TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by ATK3Shape** [Sitecore/jss#790]
## Description
When not using graphql feature npm run build fails with following error:
```
> Build error occurred
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Projects\TEMP\test-jss-next\node_modules\node-fetch\lib\index.js:1305:9)
    at C:\Projects\TEMP\test-jss-next\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (C:\Projects\TEMP\test-jss-next\node_modules\node-fetch\lib\index.js:1407:9)
    at fetch (C:\Projects\TEMP\test-jss-next\node_modules\cross-fetch\dist\node-ponyfill.js:10:20)
    at C:\Projects\TEMP\test-jss-next\node_modules\@sitecore-jss\sitecore-jss\node_modules\graphql-request\dist\index.js:123:42
    at step (C:\Projects\TEMP\test-jss-next\node_modules\@sitecore-jss\sitecore-jss\node_modules\graphql-request\dist\index.js:63:23)
    at Object.next (C:\Projects\TEMP\test-jss-next\node_modules\@sitecore-jss\sitecore-jss\node_modules\graphql-request\dist\index.js:44:53)
    at C:\Projects\TEMP\test-jss-next\node_modules\@sitecore-jss\sitecore-jss\node_modules\graphql-request\dist\index.js:38:71
    at new Promise (<anonymous>) {
  type: 'TypeError'
}
```
I assume it is related to `graphQLEndpoint="/sitecore/api/graph/edge"`

## Expected behavior
I expect to not have this error or have option to skip qraphql

## Steps To Reproduce

1. Run 'jss create test-jss-nextjs-app nextjs'
2. Run 'cd test-jss-nextjs-app'
3. Run 'npm run build'

## Your Environment

* Sitecore Version: 10
* JSS Version: 18.0.0
* Browser Name and version:
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if available):

**Comment by nickwesselman** [comment]
With Next.js, running a build will trigger a production build, which requires a service to communicate with first. The `build` target by default then needs a running Sitecore instance configured in the `scjssconfig.json`.

What you want instead likely is `npm run start`, which will start the disconnected/mock Sitecore service and run Next.js in development mode against that.

**Comment by nickwesselman** [comment]
We will log something internally to improve this error message.
